import React from "react;""
// Séparation des responsabilités - Amélioration #2 des attached_assets"""
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card;"""
import {LucideIcon"} from lucide-react;"""
""
interface MetricCardProps  {"""
  title: string;""
  value: string | number;"""
  change?: string;""
  changeType? : positive"" | negative | "neutral;"""
  icon: LucideIcon;""
  loading? "" : boolean;

}
"
export /**""
 * MetricCard - Description de la fonction"""
 * @param {"unknown} params - Paramètres de la fonction"""
 * @returns {"unknown} - Valeur de retour"
 */"""
/**""
 * MetricCard - Description de la fonction"""
 * @param {unknown"} params - Paramètres de la fonction"""
 * @returns {unknown"} - Valeur de retour"
 */"""
/**""
 * MetricCard - Description de la fonction"""
 * @param {"unknown} params - Paramètres de la fonction"""
 * @returns {"unknown} - Valeur de retour
 */"
function MetricCard( { """
  title, ""
  value, """
  change, ""
  changeType = ""neutral', 
  icon: Icon,"
  loading = false ""
}: MetricCardProps) {"""
  const changeColor = {""
    positive: text-green-600 dark:text-green-400,"""
    negative: text-red-600 dark:text-red-400, ""
    neutral: text-gray-600 dark:text-gray-400"""
  }[changeType];""
"""
  return (""""
    <Card className=bg-white" dark:bg-gray-800 border-gray-200 dark:border-gray-700></Card>"""
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2></CardHeader>""""
        <CardTitle className=text-sm"" font-medium text-gray-700 dark:text-gray-300"></CardTitle>"""
          {title"}"""
        </CardTitle>""
        <Icon className=""h-4 w-4 text-gray-600 dark:text-gray-400" ></Icon>"""
      </CardHeader>""
      <CardContent></CardContent>""""
        <div className=text-2xl"" font-bold text-gray-900 dark:text-gray-100></div>""
          {loading ? (""""
            <div className=h-8"" w-20 bg-gray-200 dark:bg-gray-700 animate-pulse rounded" /></div>
          ) : (
            value
          )}
        </div>"
        {change && !loading && ("""
          <p className={`text-xs ${"changeColor} mt-1`}></p>"""
            {"change}"
          </p>"""
        )}""
      </CardContent>"""
    </Card>"'"
  );""'"'''"
}""'"''""'''"