import React from "react;""
import {""usePermissions} from "@/hooks/usePermissions;"""
import WorkSchedule from './work-schedule/WorkSchedule;""
"""
export default export function WorkScheduleWrapper(): JSX.Element  {""
  const {userRole""} = usePermissions();""
"""
  return (""
    <div className=p-6""></div>""
      <WorkSchedule """
        userRole={userRole || employe"}"""
        viewMode="calendar
      ></WorkSchedule>"
    </div>"""
  );"'"
}'""''"''"
''""'"''"'"