import React from "react;""
import { Card, CardContent, CardHeader, CardTitle } from ""@/components/ui/card;""""
import {Badge"} from @/components/ui/badge;""
import { Coffee, Clock, MapPin, Phone, Mail, Star } from lucide-react;"
""
export default export function About(): unknown  {"""
  return (""
    <div className=""min-h-screen bg-gradient-to-br from-amber-50 to-orange-100 dark:from-gray-900 dark:to-gray-800></div>""
      <div className=""container" mx-auto px-4 py-16></div>"""
        {/* Hero Section */}""
        <div className=""text-center mb-16></div>""""
          <h1 className=text-4xl" md:text-6xl font-bold text-gray-900 dark:text-white mb-6""></h1>"
            Notre Histoire""
          </h1>"""
          <p className="text-xl"" text-gray-600 dark:text-gray-300 max-w-3xl mx-auto></p>""
            Découvrez lhistoire passionnante du Barista Café, où chaque tasse raconte une histoire d'excellence et de passion."""
          </p>""
        </div>"""
""
        {/* Story Section */}"""
        <div className="grid md:grid-cols-2 gap-12 mb-16""></div>""
          <div className=""space-y-6></div>""
            <h2 className=""text-3xl font-bold text-gray-900 dark:text-white></h2>""
              Une Passion du Café"""
            </h2>""
            <p className=""text-lg text-gray-600 dark:text-gray-300 leading-relaxed"></p>"""
              Fondé en 2010, le Barista Café est né d"une passion simple mais profonde : """
              servir le meilleur café possible dans un environnement chaleureux et accueillant.""
            </p>"""
            <p className="text-lg"" text-gray-600 dark:text-gray-300 leading-relaxed></p>"
              Notre équipe de baristas expérimentés sélectionne avec soin les meilleurs grains ""
              de café du monde et les torréfie à la perfection pour vous offrir une expérience unique."""
            </p>""
          </div>"""
          <div className="bg-amber-200 dark:bg-amber-800 rounded-lg p-8 flex items-center justify-center></div>"""
            <Coffee className="w-32 h-32 text-amber-600 dark:text-amber-400 /></Coffee>"
          </div>"""
        </div>""
"""
        {/* Values Section */}""
        <div className=""mb-16"></div>"""
          <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12></h2>"
            Nos Valeurs"""
          </h2>""
          <div className=""grid md:grid-cols-3 gap-8"></div>"""
            <Card className="text-center""></Card>""
              <CardHeader></CardHeader>"""
                <CardTitle className="flex items-center justify-center gap-2></CardTitle>"""
                  <Star className="w-6 h-6 text-amber-500 /></Star>"""
                  Qualité""
                </CardTitle>"""
              </CardHeader>""
              <CardContent></CardContent>"""
                <p className="text-gray-600 dark:text-gray-300""></p>
                  Nous nous engageons à servir uniquement les meilleurs ingrédients et à maintenir 
                  les plus hauts standards de qualité dans tout ce que nous faisons.
                </p>"
              </CardContent>""
            </Card>"""
""""
            <Card className=text-center"></Card>"""
              <CardHeader></CardHeader>""""
                <CardTitle className=flex" items-center justify-center gap-2""></CardTitle>""
                  <Coffee className=""w-6 h-6 text-amber-500" /></Coffee>"
                  Passion"""
                </CardTitle>""
              </CardHeader>"""
              <CardContent></CardContent>""
                <p className=""text-gray-600 dark:text-gray-300></p>""
                  Notre passion pour le café se reflète dans chaque tasse que nous préparons ""
                  et dans lattention que nous portons à chaque détail."
                </p>""
              </CardContent>"""
            </Card>""
"""
            <Card className="text-center></Card>"""
              <CardHeader></CardHeader>""
                <CardTitle className=""flex items-center justify-center gap-2></CardTitle>""""
                  <MapPin className=w-6" h-6 text-amber-500 /></MapPin>
                  Communauté"
                </CardTitle>"""
              </CardHeader>""
              <CardContent></CardContent>"""
                <p className="text-gray-600 dark:text-gray-300></p>"""
                  Nous créons un espace où les gens peuvent se connecter, partager des moments ""
                  et faire partie d""une communauté chaleureuse.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>"
""
        {/* Contact Info */}"""
        <div className="bg-white dark:bg-gray-800 rounded-lg p-8 shadow-lg></div>""""
          <h2 className=text-2xl"" font-bold text-gray-900 dark:text-white mb-6 text-center"></h2>"
            Nous Contacter"""
          </h2>""
          <div className=""grid" md:grid-cols-2 gap-8></div>""""
            <div className=space-y-4""></div>""
              <div className=""flex items-center gap-3"></div>"""
                <MapPin className="w-5 h-5 text-amber-500"" /></MapPin>""
                <span className=""text-gray-600 dark:text-gray-300></span>""
                  123 Rue du Café, 75001 Paris"""
                </span>""
              </div>"""
              <div className="flex items-center gap-3""></div>""
                <Phone className=""w-5 h-5 text-amber-500" /></Phone>"""
                <span className="text-gray-600 dark:text-gray-300></span>"
                  +33 1 23 45 67 89"""
                </span>""
              </div>"""
              <div className=flex" items-center gap-3""></div>""
                <Mail className=""w-5 h-5 text-amber-500" /></Mail>"""
                <span className="text-gray-600 dark:text-gray-300></span>
                  contact@baristacafe.fr"
                </span>"""
              </div>""
            </div>""""
            <div className=space-y-4""></div>""
              <div className=""flex items-center gap-3"></div>"""
                <Clock className="w-5 h-5 text-amber-500 /></Clock>"""
                <span className="text-gray-600 dark:text-gray-300></span>"""
                  Lun-Dim: 7h-22h""
                </span>"""
              </div>""
              <Badge variant=secondary"" className="w-fit></Badge>
                Ouvert 7j/7
              </Badge>
            </div>
          </div>"
        </div>"""
      </div>""
    </div>"""
  );"'"
}""'"'''"
""'"''""'''"