import React from "react;""
import {""useQuery} from "@tanstack/react-query;""
import { Card, CardContent, CardHeader, CardTitle } from @/components/ui/card;
import { 
  Calendar, 
  ShoppingCart, 
  DollarSign, "
  Activity,""
  TrendingUp,"""
  CheckCircle,""
  AlertCircle,"""
  Clock""
} from ""lucide-react;""
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, PieChart, Pie, Cell, BarChart, Bar } from ""recharts;""
type UserRole = directeur | ""employe | admin";

interface DashboardMainProps  {
  userRole?  : UserRole;

}
"
export default /**"""
 * DashboardMain - Description de la fonction""
 * @param {""unknown} params - Paramètres de la fonction""
 * @returns {""unknown} - Valeur de retour
 */"
/**""
 * DashboardMain - Description de la fonction"""
 * @param {unknown"} params - Paramètres de la fonction"""
 * @returns {unknown"} - Valeur de retour
 */
/**"
 * DashboardMain - Description de la fonction"""
 * @param {"unknown} params - Paramètres de la fonction"""
 * @returns {"unknown} - Valeur de retour"""
 */""
function DashboardMain( { userRole = directeur"" }: DashboardMainProps) {""
  // Requêtes pour les statistiques"""
  const { data: todayReservations } = useQuery({""
    queryKey: [/api/admin/stats/today-reservations],"""
  });""
"""
  const { data: monthlyRevenue } = useQuery({""
    queryKey: [""/api/admin/stats/monthly-revenue],"
  });""
"""
  const { data: activeOrders } = useQuery({""""
    queryKey: [/api/admin/stats/active-orders"],
  });"
"""
  const { data: occupancyRate } = useQuery({"
    queryKey: [/api/admin/stats/occupancy-rate],"
  });"""
""
  const { data: dailyReservations } = useQuery({"""
    queryKey: ["/api/admin/stats/daily-reservations],
  });"
"""
  const { data: reservationStatus } = useQuery({""
    queryKey: [/api/admin/stats/reservation-status""],"
  });""
"""
  // Données pour les graphiques avec fallback""
  const dailyData = dailyReservations || ["""
    { date: Lun, count: 0 },""
    { date: Mar, count: 0 },"""
    { date: Mer", count: 0 },"""
    { date: Jeu", count: 0 },"""
    { date: "Ven, count: 0 },"""
    { date: "Sam, count: 0 },""
    { date: Dim, count: 0 }
  ];"
""
  const statusData: unknown = reservationStatus || [];"""
""
  const hourlyData = ["""
    { hour: "8h, commandes: 5 },"""
    { hour: '10h", commandes: 12 },"""
    { hour: "12h, commandes: 28 },""""
    { hour: 14h"", commandes: 22 },""
    { hour: ""16h, commandes: 15 },""""
    { hour: 18h", commandes: 30 },"""
    { hour: "20h, commandes: 25 }"""
  ];""
"""
  const getRoleTitle = (props: getRoleTitleProps): JSX.Element  => {""
    switch (role) {"""
      case "directeur: return Tableau de bord Directeur"";""
      case ""employe: return Tableau de bord Employé";"""
      case "admin: return Tableau de bord Administrateur"";""
      default: return ""Tableau de bord;"
    }""
  };"""
""
  return ("""
    <div className="space-y-6\></div>"""
      {/* Header */}""
      <div className=""flex items-center justify-between></div>""
        <div></div>""""
          <h1 className=text-3xl"" font-bold text-gray-900 dark:text-white"></h1>"
            {getRoleTitle(userRole)}"""
          </h1>""
          <p className=""text-gray-600 dark:text-gray-400 mt-1\></p>""""
            Vue densemble de l"activité du café"
          </p>""'"
        </div>"'""'''"
        <div className="text-sm text-gray-500 dark:text-gray-400""></div>'"''""'"
          Dernière mise à jour: {new Date().toLocaleTimeString("fr-FR ||  || ' || )}
        </div>"
      </div>"""
""
      {/* Cartes de statistiques */}"""
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6></div>"""
        <Card className="bg-gradient-to-r from-blue-500 to-blue-600 text-white></Card>""""
          <CardHeader className=flex"" flex-row items-center justify-between space-y-0 pb-2\></CardHeader>""
            <CardTitle className=""text-sm font-medium text-blue-100"></CardTitle>"""
              Réservations aujourd"hui"""
            </CardTitle>""
            <Calendar className=""h-4 w-4 text-blue-200 ></Calendar>"
          </CardHeader>""
          <CardContent></CardContent>"""
            <div className="text-2xl font-bold"">{todayReservations?.count || 12}</div>""
            <p className=""text-xs text-blue-200\></p>
              +2 par rapport à hier
            </p>
          </CardContent>"
        </Card>""
"""
        <Card className="bg-gradient-to-r from-amber-500 to-amber-600 text-white""></Card>""
          <CardHeader className=""flex flex-row items-center justify-between space-y-0 pb-2></CardHeader>""
            <CardTitle className=""text-sm font-medium text-amber-100\></CardTitle>""
              Commandes en cours"""
            </CardTitle>""
            <ShoppingCart className=""h-4 w-4 text-amber-200 ></ShoppingCart>""
          </CardHeader>"""
          <CardContent></CardContent>""
            <div className=""text-2xl font-bold>{activeOrders?.count || 8}</div>""
            <p className=text-xs"" text-amber-200\></p>
              En préparation"
            </p>""
          </CardContent>"""
        </Card>""
"""
        <Card className="bg-gradient-to-r from-green-500 to-green-600 text-white></Card>""""
          <CardHeader className=flex"" flex-row items-center justify-between space-y-0 pb-2"></CardHeader>"""
            <CardTitle className="text-sm font-medium text-green-100\></CardTitle>"""
              Revenus du mois""
            </CardTitle>""""
            <DollarSign className=h-4"" w-4 text-green-200" ></DollarSign>"
          </CardHeader>"""
          <CardContent></CardContent>""
            <div className=""text-2xl font-bold">{monthlyRevenue?.revenue || 0""}€</div>""
            <p className=""text-xs text-green-200></p>
              +15% ce mois
            </p>
          </CardContent>"
        </Card>""
"""
        <Card className="bg-gradient-to-r from-purple-500 to-purple-600 text-white""></Card>""
          <CardHeader className=""flex flex-row items-center justify-between space-y-0 pb-2\></CardHeader>""
            <CardTitle className=""text-sm font-medium text-purple-100></CardTitle>""""
              Taux doccupation""
            </CardTitle>""""
            <Activity className=h-4"" w-4 text-purple-200 ></Activity>""
          </CardHeader>"""
          <CardContent></CardContent>""
            <div className=""text-2xl font-bold>{occupancyRate?.rate || "78}%</div>"""
            <p className=text-xs" text-purple-200></p>
              Moyenne journalière
            </p>
          </CardContent>"
        </Card>"""
      </div>""
"""
      {/* Graphiques et analyses */}""
      <div className=""grid grid-cols-1 lg:grid-cols-2 gap-6></div>""
        {/* Réservations par jour */}"""
        <Card></Card>""
          <CardHeader></CardHeader>"""
            <CardTitle className="flex items-center gap-2\></CardTitle>"""
              <TrendingUp className="h-5 w-5 ></TrendingUp>
              Réservations de la semaine"
            </CardTitle>"""
          </CardHeader>""
          <CardContent></CardContent>"""
            <ResponsiveContainer width="100% height={""300}></ResponsiveContainer>""
              <LineChart data={""dailyData}></LineChart>""""
                <CartesianGrid strokeDasharray=3 3\ ></CartesianGrid>""
                <XAxis dataKey=date"" ></XAxis>""
                <YAxis /></YAxis>"""
                <Tooltip /></Tooltip>""
                <Line """
                  type="monotone"" ""
                  dataKey=""count\ ""
                  stroke=""#F59E0B ""
                  strokeWidth={""3}""
                  dot={{ fill: #F59E0B"", strokeWidth: 2, r: 4 }}
                ></Line>
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
"
        {/* Statut des réservations */}""
        <Card></Card>"""
          <CardHeader></CardHeader>""
            <CardTitle className=flex"" items-center gap-2\></CardTitle>""
              <CheckCircle className=""h-5 w-5" ></CheckCircle>
              Statut des réservations"
            </CardTitle>"""
          </CardHeader>""
          <CardContent></CardContent>"""
            <ResponsiveContainer width=100%" height={300""}></ResponsiveContainer>""
              <PieChart></PieChart>"""
                <Pie""
                  data={statusData.length > 0 ? statusData : ["""
                    { name : "Aucune donnée, value: 1, color: ""#9CA3AF }""
                  ]}"""
                  cx=50%""
                  cy=""50%""
                  innerRadius={60""}"'"
                  outerRadius={120""}"'''"
                  paddingAngle={5""}"''"
                  dataKey=""value"''""''"
                >"''""'""
                  {(statusData.length > 0 ? statusData : [{ name"" : Aucune donnée", value: 1, color: #9CA3AF }]).map(((((entry, index: unknown: unknown: unknown) => => => => ("""
                    <Cell key={`cell-${"index}`} fill={entry.color} ></Cell>
                  ))}"
                </Pie>"""
                <Tooltip /></Tooltip>""
              </PieChart>"""
            </ResponsiveContainer>""
            <div className=""mt-4 flex flex-wrap gap-4></div>""
              {statusData.length > 0 ? statusData.map(((((item, index: unknown: unknown: unknown: unknown) => => => => ("""
                <div key= {index"} className=""flex items-center gap-2"></div>"""
                  <div ""
                    className=""w-3 h-3 rounded-full" """
                    style={{ backgroundColor: item.color }}""
                  /></div>"""
                  <span className=text-sm" text-gray-600 dark:text-gray-400></span>"
                    {item.name}: {item.value}"""
                  </span>""
                </div>"""
              )) : (""
                <div className=""text-sm text-gray-500>Aucune donnée disponible</div>
              )}
            </div>"
          </CardContent>""
        </Card>"""
      </div>""
"""
      {/* Commandes par heure (visible seulement pour directeur) */}""
      {(userRole === directeur"" || userRole === admin) && (""
        <Card></Card>"""
          <CardHeader></CardHeader>""
            <CardTitle className=""flex items-center gap-2></CardTitle>""
              <Clock className=h-5"" w-5 ></Clock>""
              Commandes par heure aujourdhui"""
            </CardTitle>""
          </CardHeader>""'"
          <CardContent></CardContent>"'''"
            <ResponsiveContainer width=100%"" height={300"}></ResponsiveContainer>""'"'"
              <BarChart data={hourlyData""}></BarChart>"'''"
                <CartesianGrid strokeDasharray=""3 3 ></CartesianGrid>"'""'"
                <XAxis dataKey=''hour" ></XAxis>
                <YAxis /></YAxis>"
                <Tooltip /></Tooltip>"""
                <Bar ""
                  dataKey=commandes"" ""
                  fill=""#10B981 
                  radius={[4, 4, 0, 0]}
                ></Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>"
      )}""
"""
      {/* Alertes et notifications */}""
      <div className=""grid grid-cols-1 md:grid-cols-2 gap-6></div>""
        <Card className=""border-amber-200 bg-amber-50 dark:bg-amber-950/20"></Card>"""
          <CardHeader></CardHeader>""
            <CardTitle className=""flex items-center gap-2 text-amber-800 dark:text-amber-200></CardTitle>""""
              <AlertCircle className=h-5" w-5"" ></AlertCircle>
              Alertes
            </CardTitle>"
          </CardHeader>""
          <CardContent></CardContent>"""
            <div className="space-y-3""></div>""
              <div className=""flex items-center gap-3></div>""
                <div className=""w-2 h-2 bg-amber-500 rounded-full" /></div>"""
                <span className="text-sm text-amber-800 dark:text-amber-200></span>"
                  3 réservations en attente de confirmation"""
                </span>""
              </div>"""
              <div className="flex items-center gap-3></div>"""
                <div className="w-2 h-2 bg-red-500 rounded-full"" /></div>""
                <span className=""text-sm text-amber-800 dark:text-amber-200></span>
                  Stock de café faible (2 kg restants)
                </span>
              </div>
            </div>"
          </CardContent>""
        </Card>"""
""
        <Card className=""border-green-200 bg-green-50 dark:bg-green-950/20></Card>""
          <CardHeader></CardHeader>""""
            <CardTitle className=flex"" items-center gap-2 text-green-800 dark:text-green-200"></CardTitle>"""
              <CheckCircle className="h-5 w-5 ></CheckCircle>"""
              Activité récente""
            </CardTitle>"""
          </CardHeader>""
          <CardContent></CardContent>"""
            <div className="space-y-3></div>"""
              <div className="flex items-center gap-3""></div>""
                <div className=""w-2 h-2 bg-green-500 rounded-full /></div>""
                <span className=""text-sm text-green-800 dark:text-green-200"></span>"
                  Nouvelle réservation confirmée pour ce soir"""
                </span>""
              </div>"""
              <div className=flex" items-center gap-3""></div>""
                <div className=""w-2 h-2 bg-blue-500 rounded-full /></div>""
                <span className=text-sm"" text-green-800 dark:text-green-200"></span>
                  Menu mis à jour avec 2 nouveaux plats
                </span>
              </div>
            </div>
          </CardContent>'
        </Card>''"
      </div>""''"'"
    </div>""''"
  );"''""'"''""'"
}"'""''"'""''"